### ISSUE TITLE
VOR will forget my apps.

### ISSUE THREAD

**Issue by nullstalgia** [SutekhVRC/VOR#3]
Hi! Let me know what logs you might need.

But sometimes the appconfig folder just empties itself on app boot/shutdown, not sure which.

**Comment by nullstalgia** [comment]
It might have to do with the location of the config files... Given how my Copy folder was ALSO wiped out. The New App was made just now to make sure I was in the right spot.

![VcVbbwC4r1](https://user-images.githubusercontent.com/20761757/210025084-2e77ae56-06b3-43de-8024-d05b94a13bd9.png)

![2022-12-29--16-16-36-explorer](https://user-images.githubusercontent.com/20761757/210023018-7d3844ad-199a-436f-8e4c-f21722556491.png)

**Comment by SutekhVRC** [comment]
Hello! This is likely another OSC app clearing the OSC folder. I have seen a few apps that do this, you should try putting a file that is not a json file in the VOR directory structure and another file that is json and then opening the other OSC apps you use and seeing if they both get deleted or only the json one.

**Comment by nullstalgia** [comment]
Oy, you're right. [OGB](https://gitlab.com/VRCFury/OscGoesBrrr/-/blob/main/src/main/OscConfigDeleter.ts#L36) deletes ALL JSONs on startup... 

I'll raise an issue with them as well, but is there a chance I could additionally _choose_ VOR's config path to avoid this altogether with potential future apps? A start-up argument seems like it would fit perfectly.

**Comment by SutekhVRC** [comment]
Hello! There is no option to change config paths, sorry! This project will hopefully be archived soon due to VRChat releasing OSCQuery! So I'm not doing much dev on it. But I also made an app like OGB that I just released version 2 of if you wanna try to use that for now! It's called [VibeCheck](https://github.com/SutekhVRC/VibeCheck)
