### ISSUE TITLE
Config Location

### ISSUE THREAD

**Issue by Phastor** [SutekhVRC/VOR#4]
Where does the application store its config? Checked under appdata and the program's install folder.
I Lost my config and need to know where to go to restore from backup.

**Comment by Phastor** [comment]
Upon further inspection, it doesn't appear it's retaining its config at all now. I reconfigured it, saved it, an then closed the app. The configuration was lost again when the app was relaunched.
I'm wondering if it's some kind of permissions issue wherever it's trying to save. Not sure how likely that is since I've changed nothing since the time it was actually working.

**Comment by SutekhVRC** [comment]
Ope, just saw this now. I believe we talked about this in Discord!
- Eventually ill get around to updating to use roaming.
~ Closing issue.
