### ISSUE TITLE
Crash on save v0.3.7

### ISSUE THREAD

**Issue by NovaVoidHowl** [SutekhVRC/VOR#5]
After moving the config folder to the new location (as required for 0.3.7), if I attempt to save any OSC app config the program will instantly crash/close

Note this is also true of the main VOR config save option too

**Comment by SutekhVRC** [comment]
Thank you for reporting!!

Fixing atm, new release will be out hopefully in the next half/full hour!

**Comment by SutekhVRC** [comment]
Patched in [latest release](https://github.com/SutekhVRC/VOR/releases/tag/0.3.8-beta)
