### ISSUE TITLE
Flickering 

### ISSUE THREAD

**Issue by LupyGamesTTV** [SutekhVRC/VOR#8]
All my stuff started working then the next few minuets everything breaks no matter what I do i restarted the programs and my pc and now it does it every time vor is launched, my face a eye tracking freak out, my heart rate freaks out, and my haptic vest as well, all my things go crazy and wont work anymore i dont know why its doing this 
![Screenshot 2023-12-16 164644](https://github.com/SutekhVRC/VOR/assets/154709140/acbd0bf0-3bbd-4afd-b4af-92a20ac29930)
![Screenshot 2023-12-23 174000](https://github.com/SutekhVRC/VOR/assets/154709140/74817ae1-8cce-4179-8304-d2a73dcf5f6f)
![Screenshot 2023-12-23 174011](https://github.com/SutekhVRC/VOR/assets/154709140/e37c9d12-22f6-4f0b-8c9c-7523939e6f63)
![Screenshot 2023-12-23 174022](https://github.com/SutekhVRC/VOR/assets/154709140/889b38ad-f004-4b4f-864b-337bee1e8e4d)

**Comment by LupyGamesTTV** [comment]
so update, if i stop vor after starting it, my face and eye tracking works including my heart rate but my vest dont work, and if i start it again it makes everything freak out

**Comment by SutekhVRC** [comment]
"All my stuff started working then the next few minuets everything breaks no matter what I do"

This sounds like the VRChat bug that has appeared recently where OSC just stops working after reloading an avatar. Reloading includes switching avatars / loading into a world / reloading avatar / etc.

You should:
1. Check that all your apps are configured correctly within the applications themselves. (Each app should be listening on the ports you set for them in VOR)
2. Try a single app alone and see if it works.
